### ISSUE TITLE
Dashboard graphics dont show correctly

### ISSUE THREAD

**Issue by KenwoodFox** [FRC-1721/pre2022season#12]
Dashboard javascript does not render correctly/code is incomplete.

Yeah its my fault but, this is a good #firstissue

![image](https://user-images.githubusercontent.com/31870999/152044564-538150f3-ff1f-49f5-8b26-7437b866d93e.png)

**Comment by KenwoodFox** [comment]
The relevant code is here: https://github.com/FRC-1721/pre2022season/blob/61288a9c3116f100d8955512d94a3772402ea747/dashboard/www/index.html#L143-L205

**Comment by prtdh** [comment]
hey i wanna fix this can u elaborate what the issue properly?

**Comment by KenwoodFox** [comment]
Sure thing, we're trying to replace the black squares with the png wheel graphics. Right now the JavaScript dosent rotate the icons around their center.

To test and simulate, run the robot code and the dashboard code at the same time, the readme under dashboard/ should detail how to get that going

**Comment by KenwoodFox** [comment]
Updated the readme a little, lmk if anything goes wrong! https://github.com/FRC-1721/pre2022season/tree/commands/dashboard#readme

**Comment by KenwoodFox** [comment]
Closed in #13
